sudo: required
services:
  - docker

script:
  - docker build -t dilipagheda/myreads  ./
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dilipagheda/myreads

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app:  "myreads"
  env:  "Myreads-env"
  bucket_name:  "elasticbeanstalk-ap-southeast-2-304346242490"
  bucket_path:  "myreads"
  on:
    branch:
      master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:  
    secure: "$AWS_SECRET_KEY"
